// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8BfmG109Iv2xtlUObzqfDCulgAQEJMw',
    appId: '1:65406507313:android:6bbed6b8ec3844b688f810',
    messagingSenderId: '65406507313',
    projectId: 'store-thing-6dcaa',
    storageBucket: 'store-thing-6dcaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNoLRLrNY5GuGtyOjmiCp_5dzhvIw654',
    appId: '1:65406507313:ios:62cf503dbe250a2c88f810',
    messagingSenderId: '65406507313',
    projectId: 'store-thing-6dcaa',
    storageBucket: 'store-thing-6dcaa.appspot.com',
    iosBundleId: 'com.store-thing.storeThing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNoLRLrNY5GuGtyOjmiCp_5dzhvIw654',
    appId: '1:65406507313:ios:d6dce3d59bde8a7788f810',
    messagingSenderId: '65406507313',
    projectId: 'store-thing-6dcaa',
    storageBucket: 'store-thing-6dcaa.appspot.com',
    iosBundleId: 'com.store-thing.storeThing.RunnerTests',
  );
}
